[project]
name = "scheduled-flow-matching"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "absl-py>=2.4.0",
    "clean-fid>=0.1.35",
    "lightning-bolts>=0.7.0",
    "matplotlib>=3.10.9",
    "numpy>=2.4.5",
    "pot>=0.9.6.post1",
    "scanpy>=1.12.1",
    "scikit-learn>=1.8.0",
    "scipy>=1.17.1",
    "scprep>=1.1.0",
    "torch>=1.11.0",
    "torchdiffeq>=0.2.5",
    "torchdyn>=1.0.6",
    "torchvision>=0.11.0",
]
[tool.pytest.ini_options]
addopts = [
  "--color=yes",
  "--durations=0",
  "--strict-markers",
  "--doctest-modules",
]
filterwarnings = [
  "ignore::DeprecationWarning",
  "ignore::UserWarning",
]
log_cli = "True"
markers = [
  "slow: slow tests",
]
minversion = "6.0"
testpaths = "tests/"

[tool.coverage.report]
exclude_lines = [
    "pragma: nocover",
    "raise NotImplementedError",
    "raise NotImplementedError()",
    "if __name__ == .__main__.:",
]

[tool.ruff]
line-length = 99

[tool.ruff.lint]
ignore = ["C901", "E501", "E741", "W605", "C408", "E402"]
select = ["C", "E", "F", "I", "W"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["E402", "F401", "F403", "F811"]

[tool.ruff.lint.isort]
known-first-party = ["src"]
known-third-party = ["torch", "transformers", "wandb"]
